project_id = "postconet"
[api]
enabled = true
port = 54321
[db]
port = 54322
[studio]
enabled = true
port = 54323
[inbucket]
enabled = true
port = 54324
[auth]
enabled = true
site_url = "postconet://auth/callback"
additional_redirect_urls = ["http://127.0.0.1", "postconet://oauth/callback"]
enable_signup = true
[auth.email]
enable_signup = true
enable_confirmations = true
[realtime]
enabled = true
